### PR TITLE
Add script path to inc

### PR DESCRIPTION
**Pull request by mdeweerd**
Added some code to the Perl script so that the include path does not need to be set externally.

Also edited the readme.md to improve the formatting.  
The comments with regards to the include path were not removed.

### CODE REVIEW

**Comment by snoopyjc** [comment]
This didn't work for me.  I have it working in my version: https://github.com/snoopyjc/pythonizer

**Comment by mdeweerd** [comment]
@snoopyjc I do not know how it didn't work for you, but using __FILE__ helps avoid some libraries, 

I wouldn't add a test of PERL5PATH because you can't know what its contents is and it may containe multiple paths in which case exists would not work and you're overriding the PERL5PATH, not appending to it.  

I am leaving this request open as a reminder to the author about this possibility - he'es free to integrate it or not, and possibly improve on it with your feedback.

**Comment by snoopyjc** [comment]
I only write to PERL5PATH if it doesn't exist.  I guess I could append to it if it exists.  Do you know what entries are separated with?

**Comment by mdeweerd** [comment]
On windows paths are separated using ';' and on *nix using ':' .

This is an example of how to get the separator:
```bash
perl -e 'use Config; print $Config{path_sep}'
```

**Comment by snoopyjc** [comment]
Thanks - I made this change which will be in my next version:

    BEGIN {                                                 # SNOOPYJC
        use Config;
        unshift @INC, dirname(__FILE__);
        if(exists $ENV{PERL5PATH}) {
            my $sep = $Config{path_sep};
            $ENV{PERL5PATH} .= $sep . dirname(__FILE__);
        } else {
            $ENV{PERL5PATH} = dirname(__FILE__);
        }
    }

**Comment by snoopyjc** [comment]
Fixed in https://github.com/snoopyjc/pythonizer

**Pull request closed without merging**
